// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-loOhaFwoEGFnmIO118NgNFKpxZ1NOE',
    appId: '1:771595173431:web:5af9fefd94033b3b7509b2',
    messagingSenderId: '771595173431',
    projectId: 'sound-mp3-70578',
    authDomain: 'sound-mp3-70578.firebaseapp.com',
    storageBucket: 'sound-mp3-70578.firebasestorage.app',
    measurementId: 'G-WH1KV3E5K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKOd2_uInQd2dk_zPx8gQGXBzA8hX9HA',
    appId: '1:771595173431:android:37b56acbad2a60e47509b2',
    messagingSenderId: '771595173431',
    projectId: 'sound-mp3-70578',
    storageBucket: 'sound-mp3-70578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpA38NVx6OsYyQrLhrFB1mVP2kSOAUZXo',
    appId: '1:771595173431:ios:36a51224ac7a43e97509b2',
    messagingSenderId: '771595173431',
    projectId: 'sound-mp3-70578',
    storageBucket: 'sound-mp3-70578.firebasestorage.app',
    iosBundleId: 'com.example.soundMp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpA38NVx6OsYyQrLhrFB1mVP2kSOAUZXo',
    appId: '1:771595173431:ios:36a51224ac7a43e97509b2',
    messagingSenderId: '771595173431',
    projectId: 'sound-mp3-70578',
    storageBucket: 'sound-mp3-70578.firebasestorage.app',
    iosBundleId: 'com.example.soundMp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY-loOhaFwoEGFnmIO118NgNFKpxZ1NOE',
    appId: '1:771595173431:web:00ef42cc42ee5bc77509b2',
    messagingSenderId: '771595173431',
    projectId: 'sound-mp3-70578',
    authDomain: 'sound-mp3-70578.firebaseapp.com',
    storageBucket: 'sound-mp3-70578.firebasestorage.app',
    measurementId: 'G-W6ZC0ZJ46Q',
  );

}